# Generated by Django 3.0.6 on 2020-06-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_module_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='object_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
